# Generated by Django 2.2.16 on 2020-09-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200930_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hygfhgfj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fghgfhfhg', models.BigIntegerField()),
            ],
        ),
    ]
